version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - database
